import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Physical AI & Humanoid Robotics - Sidebar Configuration
 * 
 * Organized by chapters with clear navigation structure
 */
const sidebars: SidebarsConfig = {
  mainSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: '📖 Introduction',
    },
    {
      type: 'category',
      label: '⚡ Chapter 1: Foundations & Sensing',
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Chapter 1: Foundations & Sensing',
        description: 'The principles of Embodied Intelligence, Physical Laws, Real-Time Systems, and internal/external sensing.',
        slug: '/01-foundations',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: '01-foundations',
        },
      ],
    },
    {
      type: 'category',
      label: '🔗 Chapter 2: ROS 2 Nervous System',
      collapsed: true,
      link: {
        type: 'generated-index',
        title: 'Chapter 2: The Robotic Nervous System (ROS 2)',
        description: 'Architecture of Nodes, Topics, Services, and Actions for robot communication.',
        slug: '/02-ros2',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: '02-ros2',
        },
      ],
    },
    {
      type: 'category',
      label: '🌐 Chapter 3: Digital Twin & Simulation',
      collapsed: true,
      link: {
        type: 'generated-index',
        title: 'Chapter 3: The Digital Twin (Simulation)',
        description: 'Mastering physics simulation with Gazebo and high-fidelity visualization.',
        slug: '/03-simulation',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: '03-simulation',
        },
      ],
    },
    {
      type: 'category',
      label: '🧠 Chapter 4: Advanced AI & Control',
      collapsed: true,
      link: {
        type: 'generated-index',
        title: 'Chapter 4: Advanced AI & Control (NVIDIA Isaac)',
        description: 'GPU-accelerated pipelines for Visual SLAM and synthetic data generation.',
        slug: '/04-isaac',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: '04-isaac',
        },
      ],
    },
    {
      type: 'category',
      label: '🤖 Chapter 5: Humanoid Action & VLA',
      collapsed: true,
      link: {
        type: 'generated-index',
        title: 'Chapter 5: Humanoid Action & VLA Integration',
        description: 'Bipedal Locomotion, Manipulation, and Vision Language Model integration.',
        slug: '/05-humanoid',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: '05-humanoid',
        },
      ],
    },
    {
      type: 'doc',
      id: 'conclusion',
      label: '🎯 Conclusion',
    },
  ],
};

export default sidebars;
